version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest    # 若要 EE 改 gitlab-ee
    container_name: gitlab
    restart: always
    hostname: "localhost"
    ports:
      - "8080:80"     # Web UI
      - "443:443"     # HTTPS
      - "22:22"       # SSH for Git clone
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    environment:
      GITLAB_ROOT_PASSWORD: "root01080710"
      GITLAB_OMNIBUS_CONFIG: |
        ## SMTP 設定，系統所有通知與驗證信都會使用這個帳號寄送
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "zxcvbnm951654@gmail.com"
        gitlab_rails['smtp_password'] = "peterrex01080710"
        gitlab_rails['smtp_domain'] = "gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_email_from'] = "zxcvbnm951654@gmail.com"

        ## 開啟使用者註冊與 email 驗證
        gitlab_rails['gitlab_signup_enabled'] = true
        gitlab_rails['gitlab_email_confirmation_enabled'] = true
    shm_size: "256m"

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - ./runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
