services:
  postgres:
    image: postgres:latest
    container_name: record_gitea_data
    environment:
      POSTGRES_USER: root  # PostgreSQL 用戶
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # 用戶密碼
      POSTGRES_DB: postgres # 初始化資料庫名稱
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # 資料持久化
    ports:
      - "5444:5432"  # 將 PostgreSQL 端口暴露出來
    networks:
      - mynetwork
  server:
    image: gitea/gitea:latest
    container_name : gitea
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - DISABLE_SSH=false
      - DB_TYPE=postgresql
      - DB_HOST=db:5432
      - DB_NAME=postgres
      - DB_USER=root
      - DB_PASSWD=${POSTGRES_PASSWORD}
    restart: always
    networks:
      - mynetwork
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4000:3000"
      - "2000:22"
    depends_on:
      - postgres

volumes:
  gitea:
    driver: local
  postgres-data:
    driver: local

networks:
  mynetwork:
    driver: bridge